#!/usr/bin/bash
#A script who print "Best School" but it display's "Hi" at the 9th iterations

i="1"
MAX_VALUE="10"
while [[ "$i" -lt "$MAX_VALUE" ]]
do
	if [[ "$i" -eq 9 ]]; then
		echo "Hi"
	fi
	echo "Best School"
	i=$((i+1))
done
