#!/usr/bin/env bash
#A script who print to the stdout

i="1"
MAX_VALUE="11"
while [[ "$i" -lt "$MAX_VALUE" ]]
do
	if [[ "$i" -eq 4 ]]
	then 
		echo Bad luck
	elif [[ "$i" -eq 8 ]]
	then
		echo good luck
	else
		echo Best School
	fi
	((i++))
done
